services:
  php:
    build:
      context: ./
      dockerfile: ./dockerFiles/backend/Dockerfile
    container_name: back_container
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network

  frontend:
    build:
      context: ./ 
      dockerfile: ./dockerFiles/frontend/Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
  backend_data: